### PR TITLE
First draft of document Fusio setup on Nginx

### PR DESCRIPTION
**Pull request by andreas-ab**
This documentation based on my personal experience with setup Fusio on Ubuntu with Nginx. Review and verification is welcome before publishing it. Please add user "Lionux2" for review.

### CODE REVIEW

**Comment by chriskapp** [comment]
@andreas-ab thanks for this PR. I can not directly add @Lionux2 as reviewer but he can still check and comment the changes. I have just checked the content/formatting etc. and from my view everything looks fine.

**Comment by chriskapp** [comment]
So I have just merged the PR, thanks for the input and if there are furhter changes needed we can simply adjust the documentation.

**Comment by lionux2** [comment]
Dear Christoph;

I installed fusio successfully using your instructions. However, my setup
is a little different, and not directly using nginx, but WordOps (having
many tools and configuration scripts around nginx, and mainly focused on
Wordpress, but not only).
It was not really a big deal to work it out, but if you need me to tell
more about my installation, then let me know.
So far so good, and a long learning curve moving forward. You guys did so
much good work already. Impressive.

Thanks,

P.

**Comment by chriskapp** [comment]
Hi @lionux2 thanks for the great feedback, so the nginx guide was created by @andreas-ab. Iam not too familiar with WordOps so Iam not sure whether a separate installation guide would be needed but if there are some special instructions feel free to create a separate guide regading the installation. You can find all available guides at: https://github.com/apioo/fusio/tree/master/doc/setup

**Pull request merged**
